DROP TABLE PERSON

CREATE TABLE [dbo].[PERSON] (
    [Id]        INT IDENTITY(1,1) NOT NULL,
    [NOM]       VARCHAR (50) NULL,
    [EMAIL]     VARCHAR (50) NULL,
    [TELEPHONE] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);